name: Deploy Docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Deps
        run: npm ci

      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run docs:build
          touch docs/.vuepress/dist/.nojekyll

      - name: Deploy to External Repository
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.RECEPTY_DEPLOY }}
          external_repository: ruplahlava/ruplahlava.github.io
          publish_dir: ./docs/.vuepress/dist
          publish_branch: master
